# This server ID
server-id  : 0000000000
# Your Accesskey and Keysecret
accesskey  : ACCESSKEY
keysecret  : KEYSECRET


# === Ok, please close the file to start the server ===
# For non-advanced users please DO NOT change the following!!
request-url : https://www.gobsidian.com